[package]
name = "minim-core"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-channel = "0.3.31"
futures-util = "0.3.31"
minim-hotkey = { path = "../minim-hotkey" }
minim-provider = { path = "../minim-provider" }
minim-types = { path = "../minim-types" }
minim-capture = { path = "../minim-capture"}
tokio = { version = "1", features = ["rt"] }
